import Link from "next/link";
import { AtSign, KeyRound, ShieldCheck, UserRound } from "lucide-react";
import { ROUTES } from "@/constants/routes";
import type { User } from "@/types/user.type";

type Props = { user: User };

export function PraktikanProfile({ user }: Props) {
  return <section aria-labelledby="profile-heading"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Account</p><h1 id="profile-heading" className="mt-1 text-2xl font-bold tracking-tight text-slate-950">My Profile</h1><p className="mt-2 text-sm text-slate-600">Manage your account credentials and personal details.</p></div><div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_20rem]"><article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><UserRound className="h-7 w-7" aria-hidden="true" /></span><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Student account</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{user.username}</h2></div></div><dl className="mt-6 space-y-3"><div className="rounded-2xl bg-slate-50 p-4"><dt className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><AtSign className="h-4 w-4" aria-hidden="true" />Email</dt><dd className="mt-2 wrap-break-word text-sm font-medium text-slate-950">{user.email}</dd></div><div className="rounded-2xl bg-slate-50 p-4"><dt className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><ShieldCheck className="h-4 w-4" aria-hidden="true" />Account status</dt><dd className="mt-2 text-sm font-medium text-slate-950">{user.is_active ? "Active" : "Inactive"}</dd></div></dl><p className="mt-5 text-sm leading-6 text-slate-600">Student identity details are managed by your department administrators and can&apos;t be edited directly.</p></article><aside className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100 text-slate-700"><KeyRound className="h-5 w-5" aria-hidden="true" /></span><h2 className="mt-4 font-semibold text-slate-950">Password &amp; security</h2><p className="mt-2 text-sm leading-6 text-slate-600">Need to refresh your password? Keep your account safe with a strong, unique passphrase.</p><Link href={ROUTES.changePassword} className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700">Update password</Link></aside></div></section>;
}
