"""course_academic_period

Revision ID: 09c48818a1ea
Revises: a3c4d5e6f7b8
Create Date: 2026-08-06 14:10:09.052573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c48818a1ea'
down_revision: Union[str, Sequence[str], None] = 'a3c4d5e6f7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('academic_year', sa.String(length=20), nullable=False))
    op.add_column('courses', sa.Column('semester', sa.String(length=20), nullable=False))
    op.add_column('courses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_unique_constraint('uix_course_period', 'courses', ['code', 'academic_year', 'semester'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_course_period', 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.drop_column('courses', 'is_active')
    op.drop_column('courses', 'semester')
    op.drop_column('courses', 'academic_year')
    # ### end Alembic commands ###
