"""class_session_lifecycle

Revision ID: 0f9b4b07b7d4
Revises: e899f1b65d4c
Create Date: 2026-08-06 17:53:56.744775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9b4b07b7d4'
down_revision: Union[str, Sequence[str], None] = 'e899f1b65d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('attendance_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_sessions', 'attendance_status')
    # ### end Alembic commands ###
