"""session_grade_publishing

Revision ID: 9acc5f60b7dd
Revises: 09c48818a1ea
Create Date: 2026-08-06 14:15:35.933842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acc5f60b7dd'
down_revision: Union[str, Sequence[str], None] = '09c48818a1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('grades_published', sa.Boolean(), nullable=False))
    op.add_column('class_sessions', sa.Column('grades_published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('class_sessions', sa.Column('grades_published_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'class_sessions', 'users', ['grades_published_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_column('class_sessions', 'grades_published_by')
    op.drop_column('class_sessions', 'grades_published_at')
    op.drop_column('class_sessions', 'grades_published')
    # ### end Alembic commands ###
