"""module_lifecycle

Revision ID: e899f1b65d4c
Revises: 9acc5f60b7dd
Create Date: 2026-08-06 14:22:55.241098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e899f1b65d4c'
down_revision: Union[str, Sequence[str], None] = '9acc5f60b7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'is_published')
    # ### end Alembic commands ###
