name: Deploy PrakTIs to Server

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: CI - Check Frontend
        working-directory: ./frontend
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Print Success
        run: echo "CI Passed! Ready for CD to server."
